In [1]:
import pandas as pd

# 读取原始数据
df = pd.read_csv("../data/train_(A+B).csv")

# 提取 Type==1 的数据，保留原标记
df_type_1 = df[df['Type'] == 1]

# 提取其它类型数据，并统一标记为 Type=0
df_other = df[df['Type'] != 1].copy()
df_other['Type'] = 0

# 将两个部分上下拼接，并按顺序排列（Type=1在前）
df_sorted = pd.concat([df_type_1, df_other], ignore_index=True)

# 保存为新文件
df_sorted.to_csv("train_binary_sorted.csv", index=False)

# 显示前几行检查
df_sorted.head()

,I1,I2,I3,gx,gy,gz,ax,ay,az,V1real,V2real,V3real,N1,N2,N3,Type
0,1.365008,0.000000,1.025641,0.731176,0.125882,0.495294,0.004725,-0.003131,-0.009364,-200.117647,0.0,231.882353,-3592,4,4091,1
1,1.248869,0.000000,1.012067,0.634706,0.058235,0.550588,-0.000029,0.002298,-0.003475,-220.764706,0.0,228.705882,-4060,5,4438,1
2,1.184012,0.000000,1.031675,0.913529,0.137647,0.523529,-0.001594,0.009277,0.001063,-227.117647,0.0,230.294118,-4050,2,4322,1
3,1.030769,1.535042,1.013675,0.894000,0.046667,2.970667,0.005273,0.000521,-0.009749,91.800000,-246.6,100.800000,1870,-4878,1986,1
4,1.071795,1.388036,1.160684,0.404000,-0.379333,4.528667,0.013428,0.002897,-0.001628,95.400000,-244.8,90.000000,1630,-4250,1542,1